plugins:
  elasticsearch_enabled:
    default: true
    client: true
  elasticsearch_autocomplete_enabled:
    default: false
    client: true
  elasticsearch_server_ip:
    default: 'localhost'
    client: true
  elasticsearch_server_port:
    default: '9200'
    client: true
  elasticsearch_discourse_username:
    default: 'system'
    client: false
